# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cadastro', models.CharField(blank=True, null=True)),
                ('inscricao_imobiliaria', models.CharField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('tipo_cadastro', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, null=True)),
                ('alinhamento', models.CharField(blank=True, null=True)),
                ('estado_conservacao', models.CharField(blank=True, null=True)),
                ('locacao', models.CharField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, null=True)),
                ('estrutura', models.CharField(blank=True, null=True)),
                ('cobertura', models.CharField(blank=True, null=True)),
                ('paredes', models.CharField(blank=True, null=True)),
                ('revestimento_externo', models.CharField(blank=True, null=True)),
                ('vedacao_esquadrias', models.CharField(blank=True, null=True)),
                ('patrimonio_unidade', models.CharField(blank=True, null=True)),
                ('murado', models.CharField(blank=True, null=True)),
                ('passeio', models.CharField(blank=True, null=True)),
                ('ct_data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, null=True)),
                ('area_total_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('area_terreno', models.CharField(blank=True, null=True)),
                ('area_comum', models.CharField(blank=True, null=True)),
                ('area_terreno_escritura', models.CharField(blank=True, null=True)),
                ('area_construida_averbada', models.CharField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('inscricao_cartografica', models.TextField(blank=True, null=True)),
                ('nr_porta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imobiliario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImobiliarioEdificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'imobiliario_edificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImobiliarioPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario_percentual', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imobiliario_pessoa',
                'managed': False,
            },
        ),
    ]
