# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hierar_via', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, null=True)),
                ('drenagem', models.TextField(blank=True, null=True)),
                ('rede_eletrica', models.TextField(blank=True, null=True)),
                ('ext_eix', models.FloatField(blank=True, null=True)),
                ('ext_of', models.TextField(blank=True, null=True)),
                ('gab_plan', models.FloatField(blank=True, null=True)),
                ('gab_tot', models.TextField(blank=True, null=True)),
                ('iluminacao', models.TextField(blank=True, null=True)),
                ('lei_of', models.TextField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('pavimentacao_1', models.TextField(blank=True, null=True)),
                ('tipo_logr', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'logradouro',
                'managed': False,
            },
        ),
    ]
