# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('cod', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('perimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('quadra', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quadra',
                'managed': False,
            },
        ),
    ]
