# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cadastro', models.CharField(blank=True, null=True)),
                ('inscricao_cartografica', models.CharField(blank=True, max_length=35, null=True)),
                ('tipo_cadastro', models.CharField(blank=True, null=True)),
                ('situacao_cadastral', models.CharField(blank=True, null=True)),
                ('area_total_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('situacao_na_quadra', models.IntegerField(blank=True, null=True)),
                ('topografia', models.IntegerField(blank=True, null=True)),
                ('pedologia', models.IntegerField(blank=True, null=True)),
                ('ocupacao', models.IntegerField(blank=True, null=True)),
                ('patrimonio_terreno', models.IntegerField(blank=True, null=True)),
                ('murado', models.IntegerField(blank=True, null=True)),
                ('passeio', models.IntegerField(blank=True, null=True)),
                ('imune_isento_iptu', models.IntegerField(blank=True, null=True)),
                ('nro_habite_se', models.CharField(blank=True, null=True)),
                ('tipo_isencao', models.IntegerField(blank=True, null=True)),
                ('area_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('bciobservacao', models.CharField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('ct_data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('id_face_quadra', models.IntegerField(blank=True, null=True)),
                ('utilizacao_terreno', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, null=True)),
                ('georreferenciamento', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
    ]
