# Generated by Django 5.2.5 on 2025-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, null=True)),
                ('proprietario_cep', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
    ]
