# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('setor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'setor',
                'managed': False,
            },
        ),
    ]
