# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(blank=True, max_length=200, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('origem', models.BigIntegerField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=200, null=True)),
                ('id_lote', models.IntegerField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificacao',
                'managed': False,
            },
        ),
    ]
